server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


